In [1]:
import numpy as np
import pandas as pd

In [2]:
fifa = pd.read_csv('data/fifa21_raw_data_v2.csv', low_memory=False)
fifa.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [3]:
#rename column 'LongName' to 'FullName'
fifa.rename(columns={'LongName':'FullName'}, inplace=True)
fifa.head()

,ID,Name,FullName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [4]:
#set 'FullName' column as the index
fifa = fifa.set_index('FullName')

In [5]:
fifa.head()

,ID,Name,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
FullName,,,,,,,,,,,,,,,,,,,,,
Lionel Messi,158023,L. Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,...,Medium,Low,5 ★,85,92,91,95,38,65,771
C. Ronaldo dos Santos Aveiro,20801,Cristiano Ronaldo,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,...,High,Low,5 ★,89,93,81,89,35,77,562
Jan Oblak,200389,J. Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
Kevin De Bruyne,192985,K. De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,...,High,High,4 ★,76,86,93,88,64,78,207
Neymar da Silva Santos Jr.,190871,Neymar Jr,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [6]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18979 entries, Lionel Messi to Xiao Zhou
Data columns (total 76 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   photoUrl          18979 non-null  object
 3   playerUrl         18979 non-null  object
 4   Nationality       18979 non-null  object
 5   Age               18979 non-null  int64
 6   ↓OVA              18979 non-null  int64
 7   POT               18979 non-null  int64
 8   Club              18979 non-null  object
 9   Contract          18979 non-null  object
 10  Positions         18979 non-null  object
 11  Height            18979 non-null  object
 12  Weight            18979 non-null  object
 13  Preferred Foot    18979 non-null  object
 14  BOV               18979 non-null  int64
 15  Best Position     18979 non-null  object
 16  Joined            18979 non-null  object
 17  Loan Date End     1013 non-null   object
 18  Value             18979 non-null  object
 19  Wage              18979 non-null  object
 20  Release Clause    18979 non-null  object
 21  Attacking         18979 non-null  int64
 22  Crossing          18979 non-null  int64
 23  Finishing         18979 non-null  int64
 24  Heading Accuracy  18979 non-null  int64
 25  Short Passing     18979 non-null  int64
 26  Volleys           18979 non-null  int64
 27  Skill             18979 non-null  int64
 28  Dribbling         18979 non-null  int64
 29  Curve             18979 non-null  int64
 30  FK Accuracy       18979 non-null  int64
 31  Long Passing      18979 non-null  int64
 32  Ball Control      18979 non-null  int64
 33  Movement          18979 non-null  int64
 34  Acceleration      18979 non-null  int64
 35  Sprint Speed      18979 non-null  int64
 36  Agility           18979 non-null  int64
 37  Reactions         18979 non-null  int64
 38  Balance           18979 non-null  int64
 39  Power             18979 non-null  int64
 40  Shot Power        18979 non-null  int64
 41  Jumping           18979 non-null  int64
 42  Stamina           18979 non-null  int64
 43  Strength          18979 non-null  int64
 44  Long Shots        18979 non-null  int64
 45  Mentality         18979 non-null  int64
 46  Aggression        18979 non-null  int64
 47  Interceptions     18979 non-null  int64
 48  Positioning       18979 non-null  int64
 49  Vision            18979 non-null  int64
 50  Penalties         18979 non-null  int64
 51  Composure         18979 non-null  int64
 52  Defending         18979 non-null  int64
 53  Marking           18979 non-null  int64
 54  Standing Tackle   18979 non-null  int64
 55  Sliding Tackle    18979 non-null  int64
 56  Goalkeeping       18979 non-null  int64
 57  GK Diving         18979 non-null  int64
 58  GK Handling       18979 non-null  int64
 59  GK Kicking        18979 non-null  int64
 60  GK Positioning    18979 non-null  int64
 61  GK Reflexes       18979 non-null  int64
 62  Total Stats       18979 non-null  int64
 63  Base Stats        18979 non-null  int64
 64  W/F               18979 non-null  object
 65  SM                18979 non-null  object
 66  A/W               18979 non-null  object
 67  D/W               18979 non-null  object
 68  IR                18979 non-null  object
 69  PAC               18979 non-null  int64
 70  SHO               18979 non-null  int64
 71  PAS               18979 non-null  int64
 72  DRI               18979 non-null  int64
 73  DEF               18979 non-null  int64
 74  PHY               18979 non-null  int64
 75  Hits              16384 non-null  object
dtypes: int64(54), object(22)
memory usage: 11.1+ MB

In [10]:
#drop 'photoUrl' and 'playerUrl' columns
fifa = fifa.drop(fifa.columns[[2,3]], axis=1)
fifa.head(1)

,ID,Name,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
FullName,,,,,,,,,,,,,,,,,,,,,
Lionel Messi,158023,L. Messi,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,...,Medium,Low,5 ★,85,92,91,95,38,65,771

In [11]:
#find total number null values
fifa.isnull().sum()

ID                0
Name              0
Nationality       0
Age               0
↓OVA              0
               ...
PAS               0
DRI               0
DEF               0
PHY               0
Hits           2595
Length: 74, dtype: int64

In [12]:
fifa.Hits

FullName
Lionel Messi                    771
C. Ronaldo dos Santos Aveiro    562
Jan Oblak                       150
Kevin De Bruyne                 207
Neymar da Silva Santos Jr.      595
                               ...
Ao Xia                          NaN
Ben Hough                       NaN
Ronan McKinley                  NaN
Zhen'ao Wang                    NaN
Xiao Zhou                       NaN
Name: Hits, Length: 18979, dtype: object

In [13]:
##fill the null values with zeros in the 'Hits' column
fifa.Hits = fifa.Hits.fillna('0')

In [14]:
fifa.isnull().sum()

ID             0
Name           0
Nationality    0
Age            0
↓OVA           0
              ..
PAS            0
DRI            0
DEF            0
PHY            0
Hits           0
Length: 74, dtype: int64

In [16]:
#convert 'Joined' column from an object to a datetime
fifa.Joined = pd.to_datetime(fifa.Joined)

In [17]:
fifa.Joined.dtype

dtype('<M8[ns]')

In [18]:
fifa.Joined

FullName
Lionel Messi                   2004-07-01
C. Ronaldo dos Santos Aveiro   2018-07-10
Jan Oblak                      2014-07-16
Kevin De Bruyne                2015-08-30
Neymar da Silva Santos Jr.     2017-08-03
                                  ...
Ao Xia                         2018-07-13
Ben Hough                      2020-08-01
Ronan McKinley                 2019-03-08
Zhen'ao Wang                   2020-09-22
Xiao Zhou                      2019-07-29
Name: Joined, Length: 18979, dtype: datetime64[ns]

In [44]:
#select players that been with a club for more than 10 years
current_date = pd.Timestamp.now().date()
date_difference = current_date - pd.DateOffset(years=10)
players_over_10yrs = fifa.Joined < date_difference
fifa.Joined[players_over_10yrs]

FullName
Lionel Messi             2004-07-01
Manuel Neuer             2011-07-01
Karim Benzema            2009-07-09
Sergio Ramos García      2005-08-01
Sergio Agüero            2011-07-28
                            ...
Yi Luo                   2012-01-01
Kyriakos Stamatopoulos   2011-01-01
Hanlin Yao               2010-01-01
Feiya Chang              2013-01-01
Shoubo Sun               2013-02-15
Name: Joined, Length: 552, dtype: datetime64[ns]

In [46]:
fifa.Club

FullName
Lionel Messi                           \n\n\n\nFC Barcelona
C. Ronaldo dos Santos Aveiro               \n\n\n\nJuventus
Jan Oblak                           \n\n\n\nAtlético Madrid
Kevin De Bruyne                     \n\n\n\nManchester City
Neymar da Silva Santos Jr.      \n\n\n\nParis Saint-Germain
                                           ...
Ao Xia                                   \n\n\n\nWuhan Zall
Ben Hough                           \n\n\n\nOldham Athletic
Ronan McKinley                           \n\n\n\nDerry City
Zhen'ao Wang                       \n\n\n\nDalian YiFang FC
Xiao Zhou                          \n\n\n\nDalian YiFang FC
Name: Club, Length: 18979, dtype: object

In [49]:
#Remove the unnecessary newline characters from all columns
fifa.Club = fifa.Club.str.replace('\n\n\n\n','')
fifa.Club

FullName
Lionel Messi                           FC Barcelona
C. Ronaldo dos Santos Aveiro               Juventus
Jan Oblak                           Atlético Madrid
Kevin De Bruyne                     Manchester City
Neymar da Silva Santos Jr.      Paris Saint-Germain
                                       ...
Ao Xia                                   Wuhan Zall
Ben Hough                           Oldham Athletic
Ronan McKinley                           Derry City
Zhen'ao Wang                       Dalian YiFang FC
Xiao Zhou                          Dalian YiFang FC
Name: Club, Length: 18979, dtype: object

In [50]:
fifa.Height.unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [57]:
#convert 'Height' column from object to integer
fifa.Height = fifa.Height.str.replace('cm','')
fifa.Height.unique()

array(['170', '187', '188', '181', '175', '184', '191', '178', '193',
       '185', '199', '173', '168', '176', '177', '183', '180', '189',
       '179', '195', '172', '182', '186', '192', '165', '194', '167',
       '196', '163', '190', '174', '169', '171', '197', '200', '166',
       '6\'2"', '164', '198', '6\'3"', '6\'5"', '5\'11"', '6\'4"',
       '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"', '5\'4"',
       '201', '158', '162', '161', '160', '203', '157', '156', '202',
       '159', '206', '155'], dtype=object)

In [64]:
def convert_height(height):
    if height[-1] == '"':
        height = height.replace('\"', '')
        feet, inches = height.split("'")
        feet_to_cm = float(feet) * 30.48
        inches_to_cm = float(inches) * 2.54
        total_cm = feet_to_cm + inches_to_cm
        return int(total_cm)
    else:
        return int(height)

In [128]:
fifa.Height = fifa.Height.apply(convert_height)

In [69]:
fifa.Height.unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 162,
       201, 158, 161, 160, 203, 157, 156, 202, 159, 206, 155], dtype=int64)

In [74]:
fifa = fifa.rename(columns={'Height':'Height - cm'})

In [75]:
fifa.Weight.unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [80]:
#convert 'Weight' column from object to integer
fifa.Weight = fifa.Weight.str.replace('kg','')
fifa.Weight.unique()

array(['72', '83', '87', '70', '68', '80', '71', '91', '73', '85', '92',
       '69', '84', '96', '81', '82', '75', '86', '89', '74', '76', '64',
       '78', '90', '66', '60', '94', '79', '67', '65', '59', '61', '93',
       '88', '97', '77', '62', '63', '95', '100', '58', '183lbs',
       '179lbs', '172lbs', '196lbs', '176lbs', '185lbs', '170lbs',
       '203lbs', '168lbs', '161lbs', '146lbs', '130lbs', '190lbs',
       '174lbs', '148lbs', '165lbs', '159lbs', '192lbs', '181lbs',
       '139lbs', '154lbs', '157lbs', '163lbs', '98', '103', '99', '102',
       '56', '101', '57', '55', '104', '107', '110', '53', '50', '54',
       '52'], dtype=object)

In [84]:
#convert lbs to kg
def convert_lbs(w):
    if 'lbs' in w:
        w = w.replace('lbs','')
        w_to_kg = int(w) * 0.453
        return int(w)
    else:
        return int(w)

In [87]:
fifa.Weight = fifa.Weight.apply(convert_lbs)

In [88]:
fifa.Weight.unique()

array([ 72,  83,  87,  70,  68,  80,  71,  91,  73,  85,  92,  69,  84,
        96,  81,  82,  75,  86,  89,  74,  76,  64,  78,  90,  66,  60,
        94,  79,  67,  65,  59,  61,  93,  88,  97,  77,  62,  63,  95,
       100,  58, 183, 179, 172, 196, 176, 185, 170, 203, 168, 161, 146,
       130, 190, 174, 148, 165, 159, 192, 181, 139, 154, 157, 163,  98,
       103,  99, 102,  56, 101,  57,  55, 104, 107, 110,  53,  50,  54,
        52], dtype=int64)

In [90]:
fifa = fifa.rename(columns={'Weight':'Weight - kg'})

In [91]:
fifa.columns

Index(['ID', 'Name', 'Nationality', 'Age', '↓OVA', 'POT', 'Club', 'Contract',
       'Positions', 'Height - cm', 'Weight - kg', 'Preferred Foot', 'BOV',
       'Best Position', 'Joined', 'Loan Date End', 'Value', 'Wage',
       'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [93]:
fifa.Value.unique()

array(['€103.5M', '€63M', '€120M', '€129M', '€132M', '€111M', '€120.5M',
       '€102M', '€185.5M', '€110M', '€113M', '€90.5M', '€82M', '€17.5M',
       '€83.5M', '€33.5M', '€114.5M', '€78M', '€103M', '€109M', '€92M',
       '€10M', '€76.5M', '€89.5M', '€87.5M', '€79.5M', '€124M', '€114M',
       '€95M', '€92.5M', '€105.5M', '€88.5M', '€85M', '€81.5M', '€26M',
       '€21M', '€56M', '€67.5M', '€53M', '€36.5M', '€51M', '€65.5M',
       '€46.5M', '€61.5M', '€72.5M', '€77.5M', '€43.5M', '€32.5M', '€36M',
       '€32M', '€54M', '€49.5M', '€57M', '€66.5M', '€74.5M', '€71.5M',
       '€121M', '€99M', '€67M', '€86.5M', '€93.5M', '€70M', '€62M',
       '€66M', '€58M', '€44M', '€81M', '€37M', '€14.5M', '€46M', '€47.5M',
       '€52.5M', '€54.5M', '€34.5M', '€57.5M', '€51.5M', '€44.5M', '€55M',
       '€48M', '€60.5M', '€63.5M', '€61M', '€29M', '€58.5M', '€55.5M',
       '€42M', '€40.5M', '€43M', '€45.5M', '€34M', '€26.5M', '€42.5M',
       '€35.5M', '€45M', '€41.5M', '€40M', '€11M', '€13.5M', '€29.5M',
       '€27M', '€15.5M', '€38.5M', '€52M', '€33M', '€19M', '€73.5M',
       '€38M', '€35M', '€47M', '€24M', '€30.5M', '€18M', '€28M', '€25.5M',
       '€25M', '€31M', '€23.5M', '€30M', '€31.5M', '€22.5M', '€28.5M',
       '€4M', '€12.5M', '€37.5M', '€27.5M', '€16M', '€15M', '€20.5M',
       '€22M', '€3.4M', '€5M', '€56.5M', '€62.5M', '€0', '€39M', '€24.5M',
       '€21.5M', '€13M', '€8M', '€20M', '€8.5M', '€2.9M', '€9M', '€4.6M',
       '€50M', '€23M', '€18.5M', '€7M', '€19.5M', '€5.5M', '€7.5M',
       '€3.8M', '€14M', '€10.5M', '€16.5M', '€3.6M', '€9.5M', '€39.5M',
       '€17M', '€12M', '€11.5M', '€4.9M', '€3M', '€1.9M', '€6.5M',
       '€1.7M', '€2.4M', '€3.1M', '€6M', '€3.7M', '€4.7M', '€4.3M',
       '€2.1M', '€1.2M', '€1.8M', '€4.8M', '€3.2M', '€1.3M', '€825K',
       '€2.3M', '€1.5M', '€3.9M', '€2.6M', '€3.5M', '€2.8M', '€2.7M',
       '€4.4M', '€4.1M', '€950K', '€1.6M', '€625K', '€1.1M', '€4.5M',
       '€4.2M', '€2.2M', '€3.3M', '€1.4M', '€2M', '€475K', '€925K',
       '€750K', '€725K', '€2.5M', '€1M', '€350K', '€525K', '€600K',
       '€850K', '€800K', '€550K', '€250K', '€400K', '€425K', '€575K',
       '€210K', '€325K', '€900K', '€875K', '€650K', '€700K', '€500K',
       '€975K', '€375K', '€775K', '€275K', '€180K', '€450K', '€675K',
       '€150K', '€240K', '€300K', '€130K', '€220K', '€200K', '€110K',
       '€170K', '€230K', '€90K', '€120K', '€80K', '€190K', '€140K',
       '€160K', '€100K', '€60K', '€50K', '€70K', '€45K', '€35K', '€40K',
       '€25K', '€20K', '€15K', '€30K', '€9K'], dtype=object)

In [96]:
#convert 'Value' column to integer
fifa.Value = fifa.Value.str.replace('€','')
fifa.Value.unique()

array(['103.5M', '63M', '120M', '129M', '132M', '111M', '120.5M', '102M',
       '185.5M', '110M', '113M', '90.5M', '82M', '17.5M', '83.5M',
       '33.5M', '114.5M', '78M', '103M', '109M', '92M', '10M', '76.5M',
       '89.5M', '87.5M', '79.5M', '124M', '114M', '95M', '92.5M',
       '105.5M', '88.5M', '85M', '81.5M', '26M', '21M', '56M', '67.5M',
       '53M', '36.5M', '51M', '65.5M', '46.5M', '61.5M', '72.5M', '77.5M',
       '43.5M', '32.5M', '36M', '32M', '54M', '49.5M', '57M', '66.5M',
       '74.5M', '71.5M', '121M', '99M', '67M', '86.5M', '93.5M', '70M',
       '62M', '66M', '58M', '44M', '81M', '37M', '14.5M', '46M', '47.5M',
       '52.5M', '54.5M', '34.5M', '57.5M', '51.5M', '44.5M', '55M', '48M',
       '60.5M', '63.5M', '61M', '29M', '58.5M', '55.5M', '42M', '40.5M',
       '43M', '45.5M', '34M', '26.5M', '42.5M', '35.5M', '45M', '41.5M',
       '40M', '11M', '13.5M', '29.5M', '27M', '15.5M', '38.5M', '52M',
       '33M', '19M', '73.5M', '38M', '35M', '47M', '24M', '30.5M', '18M',
       '28M', '25.5M', '25M', '31M', '23.5M', '30M', '31.5M', '22.5M',
       '28.5M', '4M', '12.5M', '37.5M', '27.5M', '16M', '15M', '20.5M',
       '22M', '3.4M', '5M', '56.5M', '62.5M', '0', '39M', '24.5M',
       '21.5M', '13M', '8M', '20M', '8.5M', '2.9M', '9M', '4.6M', '50M',
       '23M', '18.5M', '7M', '19.5M', '5.5M', '7.5M', '3.8M', '14M',
       '10.5M', '16.5M', '3.6M', '9.5M', '39.5M', '17M', '12M', '11.5M',
       '4.9M', '3M', '1.9M', '6.5M', '1.7M', '2.4M', '3.1M', '6M', '3.7M',
       '4.7M', '4.3M', '2.1M', '1.2M', '1.8M', '4.8M', '3.2M', '1.3M',
       '825K', '2.3M', '1.5M', '3.9M', '2.6M', '3.5M', '2.8M', '2.7M',
       '4.4M', '4.1M', '950K', '1.6M', '625K', '1.1M', '4.5M', '4.2M',
       '2.2M', '3.3M', '1.4M', '2M', '475K', '925K', '750K', '725K',
       '2.5M', '1M', '350K', '525K', '600K', '850K', '800K', '550K',
       '250K', '400K', '425K', '575K', '210K', '325K', '900K', '875K',
       '650K', '700K', '500K', '975K', '375K', '775K', '275K', '180K',
       '450K', '675K', '150K', '240K', '300K', '130K', '220K', '200K',
       '110K', '170K', '230K', '90K', '120K', '80K', '190K', '140K',
       '160K', '100K', '60K', '50K', '70K', '45K', '35K', '40K', '25K',
       '20K', '15K', '30K', '9K'], dtype=object)

In [101]:
def value_clean(v):
    if 'M' in v:
        v = v.replace('M','')
        v = float(v) * 1000000
        return int(v)
    elif 'K' in v:
        v = v.replace('K','')
        v = float(v) * 1000
        return int(v)
    else:
        return int(v)

In [103]:
fifa.Value = fifa.Value.apply(value_clean)

In [104]:
fifa.Value.unique()

array([103500000,  63000000, 120000000, 129000000, 132000000, 111000000,
       120500000, 102000000, 185500000, 110000000, 113000000,  90500000,
        82000000,  17500000,  83500000,  33500000, 114500000,  78000000,
       103000000, 109000000,  92000000,  10000000,  76500000,  89500000,
        87500000,  79500000, 124000000, 114000000,  95000000,  92500000,
       105500000,  88500000,  85000000,  81500000,  26000000,  21000000,
        56000000,  67500000,  53000000,  36500000,  51000000,  65500000,
        46500000,  61500000,  72500000,  77500000,  43500000,  32500000,
        36000000,  32000000,  54000000,  49500000,  57000000,  66500000,
        74500000,  71500000, 121000000,  99000000,  67000000,  86500000,
        93500000,  70000000,  62000000,  66000000,  58000000,  44000000,
        81000000,  37000000,  14500000,  46000000,  47500000,  52500000,
        54500000,  34500000,  57500000,  51500000,  44500000,  55000000,
        48000000,  60500000,  63500000,  61000000,  29000000,  58500000,
        55500000,  42000000,  40500000,  43000000,  45500000,  34000000,
        26500000,  42500000,  35500000,  45000000,  41500000,  40000000,
        11000000,  13500000,  29500000,  27000000,  15500000,  38500000,
        52000000,  33000000,  19000000,  73500000,  38000000,  35000000,
        47000000,  24000000,  30500000,  18000000,  28000000,  25500000,
        25000000,  31000000,  23500000,  30000000,  31500000,  22500000,
        28500000,   4000000,  12500000,  37500000,  27500000,  16000000,
        15000000,  20500000,  22000000,   3400000,   5000000,  56500000,
        62500000,         0,  39000000,  24500000,  21500000,  13000000,
         8000000,  20000000,   8500000,   2900000,   9000000,   4600000,
        50000000,  23000000,  18500000,   7000000,  19500000,   5500000,
         7500000,   3800000,  14000000,  10500000,  16500000,   3600000,
         9500000,  39500000,  17000000,  12000000,  11500000,   4900000,
         3000000,   1900000,   6500000,   1700000,   2400000,   3100000,
         6000000,   3700000,   4700000,   4300000,   2100000,   1200000,
         1800000,   4800000,   3200000,   1300000,    825000,   2300000,
         1500000,   3900000,   2600000,   3500000,   2800000,   2700000,
         4400000,   4099999,    950000,   1600000,    625000,   1100000,
         4500000,   4200000,   2200000,   3300000,   1400000,   2000000,
          475000,    925000,    750000,    725000,   2500000,   1000000,
          350000,    525000,    600000,    850000,    800000,    550000,
          250000,    400000,    425000,    575000,    210000,    325000,
          900000,    875000,    650000,    700000,    500000,    975000,
          375000,    775000,    275000,    180000,    450000,    675000,
          150000,    240000,    300000,    130000,    220000,    200000,
          110000,    170000,    230000,     90000,    120000,     80000,
          190000,    140000,    160000,    100000,     60000,     50000,
           70000,     45000,     35000,     40000,     25000,     20000,
           15000,     30000,      9000], dtype=int64)

In [105]:
#convert 'Wage' column to integer
fifa.Wage.unique()

array(['€560K', '€220K', '€125K', '€370K', '€270K', '€240K', '€250K',
       '€160K', '€260K', '€210K', '€310K', '€130K', '€350K', '€300K',
       '€190K', '€145K', '€195K', '€100K', '€140K', '€290K', '€82K',
       '€110K', '€230K', '€155K', '€200K', '€165K', '€95K', '€170K',
       '€105K', '€115K', '€150K', '€135K', '€55K', '€58K', '€81K', '€34K',
       '€120K', '€59K', '€90K', '€65K', '€56K', '€71K', '€18K', '€75K',
       '€47K', '€20K', '€84K', '€86K', '€74K', '€78K', '€27K', '€68K',
       '€85K', '€25K', '€46K', '€83K', '€54K', '€79K', '€175K', '€43K',
       '€49K', '€45K', '€38K', '€41K', '€39K', '€23K', '€51K', '€50K',
       '€87K', '€30K', '€14K', '€69K', '€31K', '€64K', '€53K', '€35K',
       '€21K', '€28K', '€17K', '€33K', '€70K', '€32K', '€89K', '€26K',
       '€40K', '€76K', '€72K', '€48K', '€36K', '€29K', '€60K', '€16K',
       '€37K', '€24K', '€52K', '€0', '€62K', '€73K', '€63K', '€19K',
       '€1K', '€66K', '€80K', '€12K', '€2K', '€42K', '€13K', '€900',
       '€57K', '€77K', '€61K', '€22K', '€67K', '€44K', '€15K', '€11K',
       '€8K', '€850', '€10K', '€88K', '€500', '€7K', '€6K', '€9K', '€5K',
       '€700', '€950', '€750', '€3K', '€650', '€600', '€4K', '€800',
       '€550'], dtype=object)

In [106]:
fifa.Wage = fifa.Wage.str.replace('€','')
fifa.Wage.unique()

array(['560K', '220K', '125K', '370K', '270K', '240K', '250K', '160K',
       '260K', '210K', '310K', '130K', '350K', '300K', '190K', '145K',
       '195K', '100K', '140K', '290K', '82K', '110K', '230K', '155K',
       '200K', '165K', '95K', '170K', '105K', '115K', '150K', '135K',
       '55K', '58K', '81K', '34K', '120K', '59K', '90K', '65K', '56K',
       '71K', '18K', '75K', '47K', '20K', '84K', '86K', '74K', '78K',
       '27K', '68K', '85K', '25K', '46K', '83K', '54K', '79K', '175K',
       '43K', '49K', '45K', '38K', '41K', '39K', '23K', '51K', '50K',
       '87K', '30K', '14K', '69K', '31K', '64K', '53K', '35K', '21K',
       '28K', '17K', '33K', '70K', '32K', '89K', '26K', '40K', '76K',
       '72K', '48K', '36K', '29K', '60K', '16K', '37K', '24K', '52K', '0',
       '62K', '73K', '63K', '19K', '1K', '66K', '80K', '12K', '2K', '42K',
       '13K', '900', '57K', '77K', '61K', '22K', '67K', '44K', '15K',
       '11K', '8K', '850', '10K', '88K', '500', '7K', '6K', '9K', '5K',
       '700', '950', '750', '3K', '650', '600', '4K', '800', '550'],
      dtype=object)

In [107]:
def wage_clean(v):
    if 'K' in v:
        v = v.replace('K','')
        v = float(v) * 1000
        return int(v)
    else:
        return int(v)

In [109]:
fifa.Wage = fifa.Wage.apply(wage_clean)

In [110]:
fifa.Wage.unique()

array([560000, 220000, 125000, 370000, 270000, 240000, 250000, 160000,
       260000, 210000, 310000, 130000, 350000, 300000, 190000, 145000,
       195000, 100000, 140000, 290000,  82000, 110000, 230000, 155000,
       200000, 165000,  95000, 170000, 105000, 115000, 150000, 135000,
        55000,  58000,  81000,  34000, 120000,  59000,  90000,  65000,
        56000,  71000,  18000,  75000,  47000,  20000,  84000,  86000,
        74000,  78000,  27000,  68000,  85000,  25000,  46000,  83000,
        54000,  79000, 175000,  43000,  49000,  45000,  38000,  41000,
        39000,  23000,  51000,  50000,  87000,  30000,  14000,  69000,
        31000,  64000,  53000,  35000,  21000,  28000,  17000,  33000,
        70000,  32000,  89000,  26000,  40000,  76000,  72000,  48000,
        36000,  29000,  60000,  16000,  37000,  24000,  52000,      0,
        62000,  73000,  63000,  19000,   1000,  66000,  80000,  12000,
         2000,  42000,  13000,    900,  57000,  77000,  61000,  22000,
        67000,  44000,  15000,  11000,   8000,    850,  10000,  88000,
          500,   7000,   6000,   9000,   5000,    700,    950,    750,
         3000,    650,    600,   4000,    800,    550], dtype=int64)

In [112]:
#convert 'Release Clause' from object to integer
fifa['Release Clause'].unique()

array(['€138.4M', '€75.9M', '€159.4M', ..., '€59K', '€35K', '€64K'],
      dtype=object)

In [113]:
fifa['Release Clause'] = fifa['Release Clause'].str.replace('€','')
fifa['Release Clause'].unique()

array(['138.4M', '75.9M', '159.4M', ..., '59K', '35K', '64K'],
      dtype=object)

In [114]:
def rc_clean(v):
    if 'M' in v:
        v = v.replace('M','')
        v = float(v) * 1000000
        return int(v)
    elif 'K' in v:
        v = v.replace('K','')
        v = float(v) * 1000
        return int(v)
    else:
        return int(v)

In [116]:
fifa['Release Clause'] = fifa['Release Clause'].apply(rc_clean)

In [117]:
fifa['Release Clause'].unique()

array([138400000,  75900000, 159400000, ...,     59000,     35000,
           64000], dtype=int64)

In [118]:
fifa.columns

Index(['ID', 'Name', 'Nationality', 'Age', '↓OVA', 'POT', 'Club', 'Contract',
       'Positions', 'Height - cm', 'Weight - kg', 'Preferred Foot', 'BOV',
       'Best Position', 'Joined', 'Loan Date End', 'Value', 'Wage',
       'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [119]:
fifa = fifa.rename(columns={'↓OVA':'OVA'})

In [120]:
fifa.OVA

FullName
Lionel Messi                    93
C. Ronaldo dos Santos Aveiro    92
Jan Oblak                       91
Kevin De Bruyne                 91
Neymar da Silva Santos Jr.      91
                                ..
Ao Xia                          47
Ben Hough                       47
Ronan McKinley                  47
Zhen'ao Wang                    47
Xiao Zhou                       47
Name: OVA, Length: 18979, dtype: int64

In [121]:
fifa.head()

,ID,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height - cm,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
FullName,,,,,,,,,,,,,,,,,,,,,
Lionel Messi,158023,L. Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170,...,Medium,Low,5 ★,85,92,91,95,38,65,771
C. Ronaldo dos Santos Aveiro,20801,Cristiano Ronaldo,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187,...,High,Low,5 ★,89,93,81,89,35,77,562
Jan Oblak,200389,J. Oblak,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
Kevin De Bruyne,192985,K. De Bruyne,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181,...,High,High,4 ★,76,86,93,88,64,78,207
Neymar da Silva Santos Jr.,190871,Neymar Jr,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [124]:
#remove stars from 'W/F', 'SM', and 'IR' column values
#define a function to remove the stars
def remove_stars(c):
    c = c.replace('★', '')
    return c

In [125]:
fifa.IR = fifa.IR.apply(remove_stars)
fifa['SM'] = fifa['SM'].apply(remove_stars)
fifa['W/F'] = fifa['W/F'].apply(remove_stars)

In [127]:
fifa[['IR', 'SM', 'W/F']]

                              IR SM W/F
FullName
Lionel Messi                  5   4  4
C. Ronaldo dos Santos Aveiro  5   5  4
Jan Oblak                     3   1  3
Kevin De Bruyne               4   4  5
Neymar da Silva Santos Jr.    5   5  5
...                           .. ..  ..
Ao Xia                        1   2  2
Ben Hough                     1   2  2
Ronan McKinley                1   2  2
Zhen'ao Wang                  1   2  3
Xiao Zhou                     1   2  3

[18979 rows x 3 columns]